### ISSUE TITLE
这也太细了吧，这怎么更新啊

### ISSUE THREAD

**Issue by xinkeji** [parasolwaddledee/blog#1]
一个一个文件放对应的位置吗

**Comment by parasolwaddledee** [comment]
你是指什么文件？

**Comment by xinkeji** [comment]
就正常的文章更新



---原始邮件---
发件人: "Waddle ***@***.***&gt;
发送时间: 2024年3月5日(周二) 中午12:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [parasolwaddledee/blog] 这也太细了吧，这怎么更新啊 (Issue #1)




 
你是指什么文件？

**Comment by parasolwaddledee** [comment]
文章更新的话是在 [source/_posts](https://github.com/parasolwaddledee/blog/tree/main/source/_posts) 这个目录下面。

**Comment by parasolwaddledee** [comment]
是的，因为我喜欢把所有文件都放在本地（包括字体 / css / js），所以就形成了这样的文件结构。
博客文章在 source/_posts，其他板块在 source 目录下一一对应，所有图片和资源都放在 source/assets 里面。

**Comment by xinkeji** [comment]
确实特别好看👀，图片可以考虑picx绑定那个目录，其他的大概还是要自己搞，很喜欢你的源码，fork了，感谢



---原始邮件---
发件人: "Waddle ***@***.***&gt;
发送时间: 2024年3月5日(周二) 中午12:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [parasolwaddledee/blog] 这也太细了吧，这怎么更新啊 (Issue #1)




 
是的，因为我喜欢把所有文件都放在本地（包括字体 / css / js），所以就形成了这样的文件结构。
 博客文章在 source/_posts，其他板块在 source 目录下一一对应，所有图片和资源都放在 source/assets 里面。

**Comment by parasolwaddledee** [comment]
不客气~
